/* Embedded SPA HTML/CSS/JS for the delta-bridge web UI.
 *
 * Inlined as a plain C string (rather than xxd-generated) so the source tree
 * has one fewer build-time dependency. The file IS the SPA — edit here.
 *
 * Stays under ~6 KB so the whole response fits comfortably inside the
 * server's 8 KB response buffer. Vanilla JS, no framework, no third-party
 * assets, no icon set — everything renders from the inlined CSS.
 *
 * Sections:
 *   - <header>   device name + big availability indicator
 *   - <section.status>   1 Hz auto-refreshing readout of /api/state
 *   - <section.controls> slider + ON/OFF + clear-faults; POSTs to /api/control endpoints
 *   - <section.config>   form bound to /api/config; passwords masked
 *
 * Maintenance:
 *   - C string concat across lines is fine; trailing comma/space is fine.
 *   - Don't put a literal '%' anywhere (this isn't a printf string but it's
 *     easy to forget; some editors choke on long single-line concatenations).
 *   - Don't introduce a build-time minifier — the response is plenty small
 *     as-is and a minifier would add a toolchain dep we don't want.
 */
#ifndef WEB_HTML_H
#define WEB_HTML_H

#include <stddef.h>

static const char INDEX_HTML[] =
"<!DOCTYPE html>"
"<html lang=\"en\">"
"<head>"
"<meta charset=\"utf-8\">"
"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">"
"<title>delta-bridge</title>"
"<style>"
":root{--bg:#101418;--fg:#e6e8eb;--mut:#8a929a;--ok:#3ec46d;--bad:#e25555;"
"--card:#181d22;--border:#262d34;--accent:#7ab8ff;}"
"*{box-sizing:border-box}"
"body{margin:0;padding:0;background:var(--bg);color:var(--fg);"
"font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:14px;"
"line-height:1.5}"
"header{padding:14px 18px;border-bottom:1px solid var(--border);"
"display:flex;align-items:center;gap:12px;flex-wrap:wrap}"
"header h1{font-size:18px;margin:0;font-weight:600;letter-spacing:.01em}"
".pill{padding:4px 10px;border-radius:12px;font-size:12px;font-weight:600;"
"text-transform:uppercase;letter-spacing:.05em}"
".pill.ok{background:rgba(62,196,109,.15);color:var(--ok);"
"border:1px solid rgba(62,196,109,.4)}"
".pill.bad{background:rgba(226,85,85,.15);color:var(--bad);"
"border:1px solid rgba(226,85,85,.4)}"
"main{max-width:840px;margin:0 auto;padding:18px;display:grid;gap:18px}"
"section{background:var(--card);border:1px solid var(--border);"
"border-radius:8px;padding:14px 16px}"
"section h2{margin:0 0 10px;font-size:14px;font-weight:600;"
"color:var(--mut);text-transform:uppercase;letter-spacing:.08em}"
".grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));"
"gap:8px 18px}"
".k{color:var(--mut);font-size:11px;text-transform:uppercase;letter-spacing:.06em}"
".v{font-size:16px;font-weight:600;word-break:break-all}"
".v.faults{color:var(--bad)}"
".v.faults.none{color:var(--ok)}"
"form{display:grid;gap:10px}"
".row{display:grid;grid-template-columns:140px 1fr;gap:10px;align-items:center}"
"@media(max-width:520px){.row{grid-template-columns:1fr}.row label{font-size:11px}}"
"label{color:var(--mut);font-size:12px;letter-spacing:.04em}"
"input[type=text],input[type=number],input[type=password]{"
"width:100%;padding:7px 9px;background:#0c0f12;color:var(--fg);"
"border:1px solid var(--border);border-radius:5px;font:inherit}"
"input[type=range]{width:100%}"
"button{padding:8px 14px;background:var(--accent);color:#062345;"
"border:none;border-radius:5px;font:inherit;font-weight:600;cursor:pointer}"
"button:hover{filter:brightness(1.1)}"
"button.alt{background:#26313b;color:var(--fg);border:1px solid var(--border)}"
"button.warn{background:#b04848;color:#fff}"
".controls-row{display:flex;align-items:center;gap:10px;flex-wrap:wrap}"
".controls-row .v{min-width:42px;text-align:right}"
".msg{font-size:12px;padding:6px 10px;border-radius:5px;margin-top:6px;display:none}"
".msg.show{display:block}"
".msg.ok{background:rgba(62,196,109,.15);color:var(--ok)}"
".msg.err{background:rgba(226,85,85,.15);color:var(--bad)}"
".savebar{display:flex;gap:10px;flex-wrap:wrap;align-items:center}"
".note{color:var(--mut);font-size:12px}"
"</style>"
"</head>"
"<body>"
"<header>"
"<h1>delta-bridge</h1>"
"<span id=\"device\" class=\"note\"></span>"
"<span id=\"avail\" class=\"pill bad\">offline</span>"
"</header>"
"<main>"

"<section><h2>Status</h2>"
"<div class=\"grid\">"
"<div><div class=\"k\">Voltage</div><div class=\"v\" id=\"s-voltage\">--</div></div>"
"<div><div class=\"k\">Current</div><div class=\"v\" id=\"s-current\">--</div></div>"
"<div><div class=\"k\">Power</div><div class=\"v\" id=\"s-power\">--</div></div>"
"<div><div class=\"k\">Pilot State</div><div class=\"v\" id=\"s-pilot\">--</div></div>"
"<div><div class=\"k\">Pilot Duty</div><div class=\"v\" id=\"s-duty\">--</div></div>"
"<div><div class=\"k\">Rated Amps</div><div class=\"v\" id=\"s-rated\">--</div></div>"
"<div><div class=\"k\">Pri State</div><div class=\"v\" id=\"s-pri\">--</div></div>"
"<div><div class=\"k\">User State</div><div class=\"v\" id=\"s-user\">--</div></div>"
"<div><div class=\"k\">Red LED</div><div class=\"v\" id=\"s-red\">--</div></div>"
"<div><div class=\"k\">STM32 Link</div><div class=\"v\" id=\"s-link\">--</div></div>"
"<div style=\"grid-column:1/-1\"><div class=\"k\">Active Faults</div>"
"<div class=\"v faults none\" id=\"s-faults\">--</div></div>"
"</div></section>"

"<section><h2>Controls</h2>"
"<form id=\"f-amps\" onsubmit=\"return setAmps(event)\">"
"<div class=\"row\"><label for=\"amps\">Set Current (A)</label>"
"<div class=\"controls-row\">"
"<input type=\"range\" id=\"amps\" name=\"amps\" min=\"6\" max=\"30\" step=\"1\" value=\"16\""
" oninput=\"document.getElementById('amps-v').textContent=this.value\">"
"<span class=\"v\" id=\"amps-v\">16</span>"
"<button type=\"submit\">Set</button>"
"</div></div></form>"
"<div id=\"msg-amps\" class=\"msg\"></div>"

"<form id=\"f-auth\" onsubmit=\"return setAuth(event)\" style=\"margin-top:12px\">"
"<div class=\"row\"><label>Authorize</label>"
"<div class=\"controls-row\">"
"<button type=\"button\" onclick=\"sendAuth('ON')\">ON</button>"
"<button type=\"button\" class=\"alt\" onclick=\"sendAuth('OFF')\">OFF</button>"
"</div></div></form>"
"<div id=\"msg-auth\" class=\"msg\"></div>"

"<form id=\"f-clr\" onsubmit=\"return clearFaults(event)\" style=\"margin-top:12px\">"
"<div class=\"row\"><label>Faults</label>"
"<div class=\"controls-row\">"
"<button type=\"submit\" class=\"warn\">Clear faults</button>"
"</div></div></form>"
"<div id=\"msg-clr\" class=\"msg\"></div>"
"</section>"

"<section><h2>Bridge config</h2>"
"<form id=\"f-cfg\" onsubmit=\"return saveCfg(event)\">"
"<div class=\"row\"><label for=\"broker_host\">broker_host</label>"
"<input type=\"text\" id=\"broker_host\" name=\"broker_host\"></div>"
"<div class=\"row\"><label for=\"broker_port\">broker_port</label>"
"<input type=\"number\" id=\"broker_port\" name=\"broker_port\" min=\"1\" max=\"65535\"></div>"
"<div class=\"row\"><label for=\"broker_user\">broker_user</label>"
"<input type=\"text\" id=\"broker_user\" name=\"broker_user\"></div>"
"<div class=\"row\"><label for=\"broker_pass\">broker_pass</label>"
"<input type=\"password\" id=\"broker_pass\" name=\"broker_pass\""
" placeholder=\"(unchanged)\"></div>"
"<div class=\"row\"><label for=\"topic_prefix\">topic_prefix</label>"
"<input type=\"text\" id=\"topic_prefix\" name=\"topic_prefix\"></div>"
"<div class=\"row\"><label for=\"device_id\">device_id</label>"
"<input type=\"text\" id=\"device_id\" name=\"device_id\"></div>"
"<div class=\"row\"><label for=\"poll_hz\">poll_hz</label>"
"<input type=\"number\" id=\"poll_hz\" name=\"poll_hz\" min=\"1\"></div>"
"<div class=\"row\"><label for=\"write_enable\">write_enable</label>"
"<select id=\"write_enable\" name=\"write_enable\">"
"<option value=\"false\">false</option><option value=\"true\">true</option></select></div>"
"<div class=\"row\"><label for=\"web_enable\">web_enable</label>"
"<select id=\"web_enable\" name=\"web_enable\">"
"<option value=\"false\">false</option><option value=\"true\">true</option></select></div>"
"<div class=\"row\"><label for=\"web_port\">web_port</label>"
"<input type=\"number\" id=\"web_port\" name=\"web_port\" min=\"1\" max=\"65535\"></div>"
"<div class=\"row\"><label for=\"web_user\">web_user</label>"
"<input type=\"text\" id=\"web_user\" name=\"web_user\"></div>"
"<div class=\"row\"><label for=\"web_pass\">web_pass</label>"
"<input type=\"password\" id=\"web_pass\" name=\"web_pass\""
" placeholder=\"(unchanged)\"></div>"
"<div class=\"savebar\">"
"<button type=\"submit\">Save</button>"
"<button type=\"button\" class=\"warn\" id=\"btn-restart\" onclick=\"restart()\""
" style=\"display:none\">Restart bridge now</button>"
"</div>"
"</form>"
"<div id=\"msg-cfg\" class=\"msg\"></div>"
"</section>"

"</main>"
"<script>"
"function show(id,kind,text){var e=document.getElementById(id);"
"e.className='msg show '+kind;e.textContent=text;"
"setTimeout(function(){e.classList.remove('show')},4500)}"
"function postForm(url,obj){var body=Object.keys(obj).map(function(k){"
"return encodeURIComponent(k)+'='+encodeURIComponent(obj[k])}).join('&');"
"return fetch(url,{method:'POST',headers:{"
"'Content-Type':'application/x-www-form-urlencoded'},body:body})}"
"function setAmps(e){e.preventDefault();var a=document.getElementById('amps').value;"
"postForm('/api/control/rated_amps',{amps:a}).then(function(r){"
"return r.json().then(function(j){"
"show('msg-amps',j.ok?'ok':'err',j.ok?('Set to '+j.rated_amps+' A'):j.error)})});"
"return false}"
"function sendAuth(s){postForm('/api/control/authorize',{state:s}).then(function(r){"
"return r.json().then(function(j){"
"show('msg-auth',j.ok?'ok':'err',j.ok?('State: '+j.state):j.error)})})}"
"function setAuth(e){e.preventDefault();return false}"
"function clearFaults(e){e.preventDefault();"
"postForm('/api/control/clear_faults',{}).then(function(r){"
"return r.json().then(function(j){"
"show('msg-clr',j.ok?'ok':'err',j.ok?'Faults cleared':j.error)})});"
"return false}"
"function saveCfg(e){e.preventDefault();var f=document.getElementById('f-cfg');"
"var obj={};Array.from(f.elements).forEach(function(el){"
"if(!el.name)return;"
"if((el.id==='broker_pass'||el.id==='web_pass')&&el.value==='')return;"
"obj[el.name]=el.value});"
"postForm('/api/config',obj).then(function(r){return r.json().then(function(j){"
"if(j.ok){show('msg-cfg','ok','Saved. Restart bridge for changes to take effect.');"
"document.getElementById('btn-restart').style.display='inline-block';"
"loadCfg()}else{show('msg-cfg','err',j.error||'save failed')}})});"
"return false}"
"function restart(){if(!confirm('Restart delta-bridge now?'))return;"
"fetch('/api/restart',{method:'POST'}).then(function(){"
"show('msg-cfg','ok','Restarting...');"
"setTimeout(function(){location.reload()},3000)})}"
"function loadCfg(){fetch('/api/config').then(function(r){return r.json()})"
".then(function(c){"
"document.getElementById('broker_host').value=c.broker_host||'';"
"document.getElementById('broker_port').value=c.broker_port||'';"
"document.getElementById('broker_user').value=c.broker_user||'';"
"document.getElementById('broker_pass').value='';"
"document.getElementById('topic_prefix').value=c.topic_prefix||'';"
"document.getElementById('device_id').value=c.device_id||'';"
"document.getElementById('poll_hz').value=c.poll_hz||'';"
"document.getElementById('write_enable').value=c.write_enable?'true':'false';"
"document.getElementById('web_enable').value=c.web_enable?'true':'false';"
"document.getElementById('web_port').value=c.web_port||'';"
"document.getElementById('web_user').value=c.web_user||'';"
"document.getElementById('web_pass').value='';"
"})}"
"function refresh(){fetch('/api/state').then(function(r){return r.json()})"
".then(function(s){"
"var av=document.getElementById('avail');"
"if(s.availability==='online'){av.className='pill ok';av.textContent='online'}"
"else{av.className='pill bad';av.textContent='offline'}"
"document.getElementById('device').textContent=s.device_id?('device: '+s.device_id):'';"
"document.getElementById('s-voltage').textContent=s.voltage.toFixed(2)+' V';"
"document.getElementById('s-current').textContent=s.current.toFixed(2)+' A';"
"document.getElementById('s-power').textContent=s.power+' W';"
"document.getElementById('s-pilot').textContent=s.pilot_state;"
"document.getElementById('s-duty').textContent=s.pilot_duty+' %';"
"document.getElementById('s-rated').textContent=s.rated_amps+' A';"
"document.getElementById('s-pri').textContent=s.pri_state;"
"document.getElementById('s-user').textContent=s.user_state;"
"document.getElementById('s-red').textContent=s.red_led;"
"document.getElementById('s-link').textContent=s.stm32_link_ok?'ok':'fault';"
"var f=document.getElementById('s-faults');"
"f.textContent=s.active_faults;"
"f.className='v faults'+(s.active_faults==='none'?' none':'');"
"}).catch(function(){"
"document.getElementById('avail').className='pill bad';"
"document.getElementById('avail').textContent='offline';"
"})}"
"loadCfg();refresh();setInterval(refresh,1000);"
"</script>"
"</body></html>";

#define INDEX_HTML_LEN (sizeof(INDEX_HTML) - 1)

#endif /* WEB_HTML_H */
